-- ==================================================================================
-- Abschlussprojekt TierTaxi von Simone Möller, Theresa Dürbeck und Rebekka Kupffer
-- Informationen zu diesem Script: 
-- Authorin(-nen): 
-- ==================================================================================