USE [Tiertransport]
GO

/****** Object:  Table [dbo].[Tierarztprotokoll]    Script Date: 23.05.2025 15:47:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tierarztprotokoll](
	[Tap_ID] [int] IDENTITY(1,1) NOT NULL,
	[Tier_ID] [int] NULL,
 CONSTRAINT [PK_Tierarztprotokoll] PRIMARY KEY CLUSTERED 
(
	[Tap_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


