CREATE DATABASE [TierTaxi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TierTaxi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\TierTaxi.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TierTaxi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\TierTaxi_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [TierTaxi] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [TierTaxi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TierTaxi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TierTaxi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TierTaxi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TierTaxi] SET ARITHABORT OFF 
GO
ALTER DATABASE [TierTaxi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TierTaxi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TierTaxi] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [TierTaxi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TierTaxi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TierTaxi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TierTaxi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TierTaxi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TierTaxi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TierTaxi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TierTaxi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TierTaxi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TierTaxi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TierTaxi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TierTaxi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TierTaxi] SET  READ_WRITE 
GO
ALTER DATABASE [TierTaxi] SET RECOVERY FULL 
GO
ALTER DATABASE [TierTaxi] SET  MULTI_USER 
GO
ALTER DATABASE [TierTaxi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TierTaxi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TierTaxi] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TierTaxi]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [TierTaxi]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TierTaxi] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
