USE [TierTaxi]

GO

SET ANSI_PADDING ON


GO

CREATE UNIQUE NONCLUSTERED INDEX [ix_Tierart] ON [dbo].[tb_Tierart]
(
	[Tierart] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO


